# Generated by Django 4.2 on 2025-04-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevage',
            name='nom',
            field=models.CharField(default='Nom par défaut', max_length=100, unique=True),
        ),
    ]
