# Generated by Django 4.2 on 2025-04-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0004_regle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elevage',
            name='nombre_lapins_femelles',
        ),
        migrations.RemoveField(
            model_name='elevage',
            name='nombre_lapins_males',
        ),
    ]
