# Generated by Django 4.2 on 2025-04-10 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0005_remove_elevage_nombre_lapins_femelles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevage',
            name='regle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jeu.regle'),
        ),
        migrations.AddField(
            model_name='regle',
            name='consommation_nourriture_adulte',
            field=models.FloatField(default=0.25),
        ),
    ]
